adjective_1 = input("Give me an adjective.")
verb_1 = input("Give me a verb.")
noun_1 = input("Give me a noun.")
verb_2 = input("Give me a verb that ends with ed.")
adjective_2 = input("Give me another adjective.")
plural_1 = input("Give me a plural noun.")
adjective_3 = input("Give me another adjective.")
noun_2 = input("Give me another noun.")
verb_3 = input("Give me another verb.")
noun_3 = input("Give me a noun.")

print("Once there was a %s snake." % adjective_1)
print("The snake wanted to go %s" % verb_1)
print("with his friend %s" % noun_1)
print("When the got there they got %s" % verb_2)
print("by a/an %s monkey" % adjective_2)
print("two %s arrived and pushed him away" % plural_1)
print("a %s guy arrived and took the monkey" % adjective_3)
print("then a %s saw them outside and tried to fight them, but they resisted" % noun_2)
print("they got home and %s" % verb_3)
print("with their other friend %s" % noun_3)
