madlibs_list = []
madlibs_list.append(input("Give me an adjective."))
madlibs_list.append(input("Give me a verb."))
madlibs_list.append(input("Give me a noun."))
madlibs_list.append(input("Give me a verb that ends with ed."))
madlibs_list.append(input("Give me another adjective."))
madlibs_list.append(input("Give me a plural noun."))
madlibs_list.append(input("Give me another adjective."))
madlibs_list.append(input("Give me another noun."))
madlibs_list.append(input("Give me another verb."))
madlibs_list.append(input("Give me a noun."))

print("Once there was a %s snake." % adjective_1)
print("The snake wanted to go %s" % verb_1)
print("with his friend %s" % noun_1)
print("When the got there they got %s" % verb_2)
print("by a/an %s monkey" % adjective_2)
print("two %s arrived and pushed him away" % plural_1)
print("a %s guy arrived and took the monkey" % adjective_3)
print("then a %s saw them outside and tried to fight them, but they resisted" % noun_2)
print("they got home and %s" % verb_3)
print("with their other friend %s" % noun_3)
