madlibs_list = []
madlibs_list.append(input("Give me an adjective."))
madlibs_list.append(input("Give me a verb."))
madlibs_list.append(input("Give me a noun."))
madlibs_list.append(input("Give me a verb that ends with ed."))
madlibs_list.append(input("Give me another adjective."))
madlibs_list.append(input("Give me a plural noun."))
madlibs_list.append(input("Give me another adjective."))
madlibs_list.append(input("Give me another noun."))
madlibs_list.append(input("Give me another verb."))
madlibs_list.append(input("Give me a noun."))

print("Once there was a %s snake." % madlibs_list[0])
print("The snake wanted to go %s" % madlibs_list[1])
print("with his friend %s" % madlibs_list[2])
print("When the got there they got %s" % madlibs_list[3])
print("by a/an %s monkey" % madlibs_list[4])
print("two %s arrived and pushed him away" % madlibs_list[5])
print("a %s guy arrived and took the monkey" % madlibs_list[6])
print("then a %s saw them outside and tried to fight them, but they resisted" % madlibs_list[7])
print("they got home and %s" % madlibs_list[8])
print("with their other friend %s" % madlibs_list[9])
